name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      # DEBUG: verify which PostCSS config is in the repo
      - run: |
          echo "== PostCSS configs in repo =="
          ls -la postcss.config.* || true
          echo "== Show postcss.config.mjs =="
          cat postcss.config.mjs || true
          echo "== Show globals.css first lines =="
          sed -n '1,40p' src/styles/globals.css || true

      - run: npm run build   # produces /out if you set output:'export'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
